groups:
  - name: all
    jobs:
#      - build-terraform-provider-package
      - point-to-point-ci-test

shared:

  - &run
    task: terraformci
    file: terraform-provider-ks3/ci/tasks/ci-test.yml
    params:
      ALICLOUD_ACCESS_KEY: {{ksyun_access_key}}
      ALICLOUD_SECRET_KEY: {{ksyun_secret_key}}
      ALICLOUD_REGION: {{ksyun_region}}
      DING_TALK_TOKEN: {{ding_talk_token}}
      ALICLOUD_ACCOUNT_ID: {{ksyun_accound_id}}
      ALICLOUD_RESOURCE_GROUP_ID: {{ksyun_resource_group_id}}
      ALICLOUD_WAF_INSTANCE_ID: {{ksyun_waf_instance_id}}
      CONCOURSE_TARGET: {{ksyun_concourse_target}}
      CONCOURSE_TARGET_URL: {{ksyun_concourse_target_url}}
      CONCOURSE_TARGET_USER: {{ksyun_concourse_target_user}}
      CONCOURSE_TARGET_PASSWORD: {{ksyun_concourse_target_password}}
      TRIGGER_TARGET_PIPELINE: {{ksyun_trigger_target_pipeline}}
      ENTERPRISE_ACCOUNT_ENABLED: {{enterprise_account_enabled}}
      ALICLOUD_EXPRESS_CONNECT_UID: {{ksyun_express_connect_uid}}

jobs:
#  - name: build-terraform-provider-package
#    serial: true
#    plan:
#    - in_parallel:
      - get: terraform-provider-ks3
        resource: terraform-provider-ks3
#      - aggregate:
#          - *get-ksyun-cli
#      - <<: *build

- name: point-to-point-ci-test
  plan:
  - in_parallel:
    - get: terraform-provider-ks3
      resource: terraform-provider-ks3
      trigger: true
    - get: ksyun-cli
      resource: ksyun-cli
  - <<: *run

resources:
- name: terraform-provider-ks3
  type: git
  source:
    uri: https://github.com/aliyun/terraform-provider-ks3.git
    branch: master
    paths:
      - alicloud/*
      - vendor/*
      - go.mod
      - main.go

- name: ksyun-cli
  type: s3
  source:
    access_key_id: {{ksyun_cli_access_key}}
    secret_access_key: {{ksyun_cli_secret_key}}
    bucket: {{ksyun_cli_bucket}}
    regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
    region_name: {{ksyun_cli_region}}
    endpoint: oss-((ksyun_cli_region)).aliyuncs.com
