groups:
  - name: All
    jobs:
      - point-to-point-ci-test

shared:
  - &clone-provider
    get: terraform-provider-ks3
    resource: terraform-provider-ks3
    trigger: false

  - &get-ksyun-cli
    get: ksyun-cli
    resource: ksyun-cli

  - &run
    task: terraform ci
    file: terraform-provider-ks3/ci/tasks/ci-test.yml
    params:
      ALICLOUD_ACCESS_KEY: {{ksyun_access_key}}
      ALICLOUD_SECRET_KEY: {{ksyun_secret_key}}
      ALICLOUD_REGION: {{ksyun_region}}
      DING_TALK_TOKEN: {{ding_talk_token}}
      ALICLOUD_ACCOUNT_ID: {{ksyun_accound_id}}
      ALICLOUD_RESOURCE_GROUP_ID: {{ksyun_resource_group_id}}
      ALICLOUD_WAF_INSTANCE_ID: {{ksyun_waf_instance_id}}

jobs:
  - name: point-to-point-ci-test
    serial: true
    plan:
    - in_parallel:
      - get: terraform-provider-ks3
        resource: terraform-provider-ks3
      - get: ksyun-cli
        resource: ksyun-cli
      - <<: *run

resources:
- name: terraform-provider-ks3
  type: git
  source:
    uri: https://github.com/aliyun/terraform-provider-ks3.git
    branch: master
    paths:
      - ci/tasks/*

- name: ksyun-cli
  type: s3
  source:
    access_key_id: {{ksyun_cli_access_key}}
    secret_access_key: {{ksyun_cli_secret_key}}
    bucket: {{ksyun_cli_bucket}}
    regexp: .*-cli-linux-3\.0\.(\d+)-amd64\.tgz
    region_name: {{ksyun_cli_region}}
    endpoint: oss-((ksyun_cli_region)).aliyuncs.com
